### ISSUE TITLE
Theme feedback

### ISSUE THREAD

**Issue by cheesypoof** [Brackets-Themes/EasyDark#2]
I think this is one of the best dark themes; thanks for making it available.

I prefer this theme without the gutter border. Would you be open to removing it?

I find that the turquoise selection color is a bit out of place with the rest of the theme colors. Perhaps `fade(@blue, 31%)` would work better?

I can send a pull request if you agree with the suggestions.

**Comment by MiguelCastillo** [comment]
@cheesypoof Ha! cheesypoof is an awesome name!!

Yeah, I am open to making this theme awesome! Thank you for helping. If you could please provide separate PRs so that it's easier to merge specific style changes, that would be optimal.

Also, I am going to be reworking the theme so that it doesn't use the brackets imports... So, this won't be ready for a pull request right away. I will post back here when the theme is ready.

**Comment by MiguelCastillo** [comment]
@cheesypoof I am ready to get your PRs!  Maybe you could also just create an event better theme we can add it in this group for you :)
